version: '3.8'

services:
  app:
    build: .
    container_name: kara_pipeline_app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    tty: true

  db:
    image: postgres:15
    container_name: kara_pipeline_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
