kara_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "1234"
      port: 5432
      dbname: kara_dbt
      schema: staging
      threads: 4
  
