version: 2

models:
  - name: stg_telegram_messages
    description: "Staging table for cleaned telegram messages"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - unique
          - not_null
      - name: message
        tests:
          - not_null

  - name: dim_channels
    description: "Dimension table of Telegram channels"
    columns:
      - name: channel_id
        description: "Unique channel identifier"
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Dimension table for dates"
    columns:
      - name: date
        description: "Date for analysis"
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: "Fact table of Telegram messages"
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_id
        tests:
          - not_null
      - name: message_length
        tests:
          - not_null